# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libranote', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='illustration',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d'),
        ),
    ]
