# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libranote', '0003_school_illustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='X', max_length=25)),
                ('birthday', models.DateField()),
                ('avatar_url', models.ImageField(upload_to='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Level')),
                ('main_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, default='', max_length=1)),
                ('group', models.IntegerField(default=None, null=True)),
                ('day', models.CharField(default='Monday', max_length=20)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('due_week', models.IntegerField()),
                ('due_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('comment', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Account')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='libranote.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('optional', models.BooleanField()),
                ('teachers', models.ManyToManyField(to='libranote.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('show_at', models.DateField(auto_now=True)),
                ('coefficient', models.FloatField(default=1.0)),
                ('out_of', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='options',
            field=models.ManyToManyField(to='libranote.Subject'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Test'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libranote.Account'),
        ),
    ]
