# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libranote', '0006_test_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
